[package]
name = "template"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"

[dev-dependencies]
criterion = { version = "0.6.0", features = ["html_reports"] }

